name: Padoka CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validacao-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build do Frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    - name: Instalação do Backend
      working-directory: ./backend
      run: npm install

    - name: Teste de Build do Docker Compose
      run: docker compose build

  deploy:
    needs: validacao-build 
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Baixar código atualizado
      uses: actions/checkout@v4
    - name: 🔐 Configurar variáveis de ambiente (.env)
      shell: powershell
      run: |
        "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" | Out-File -FilePath .env -Encoding utf8
        "JWT_SECRET=${{ secrets.JWT_SECRET }}" | Out-File -FilePath .env -Encoding utf8 -Append
        "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" | Out-File -FilePath .env -Encoding utf8 -Append

    - name: Recriar containers (Deploy)
      run: docker compose up -d --build
